name: Package

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:

  package:
    runs-on: ubuntu-latest
    steps:
    - name: Generate snapshot date
      id: snapshot-date
      run: |
        echo ::set-output name=date::$(date -u +%Y%m%d)
        echo ::set-output name=epoch::$(date -u +%s)
      shell: bash

    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2.1.0

    - name: Build Melange Package
      uses: chainguard-dev/actions/melange-build@main
      with:
        config: melange.yaml
        archs: amd64
        sign-with-temporary-key: true

    - name: Build with apko
      uses: distroless/actions/apko-publish@main
      with:
        config: apko.yaml
        tag: ghcr.io/itsjamie9494/capybot:latest
        keyring-append: /github/workspace/melange.rsa.pub
        archs: amd64
        source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
